=== ElmarDott/TP-CORE/src/test/resources/org/europa/together/xml/simple.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.sample.com/EmployeeInfo"
            elementFormDefault="qualified">

    <xsd:element name="EmployeeInfo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Employee" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Name" type="xsd:string" />
                            <xsd:element name="Department" type="xsd:string" />
                            <xsd:element name="Telephone" type="xsd:string" />
                            <xsd:element name="Email" type="xsd:string" />
                        </xsd:sequence>
                        <xsd:attribute name="EmployeeNumber" type="xsd:int" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== ElmarDott/TP-CORE/src/test/resources/org/europa/together/xml/test_valid_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
 
<!-- Test file for XML Schema validation. -->
<e:EmployeeInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:e="http://www.sample.com/EmployeeInfo"
                xsi:schemaLocation="http://www.sample.com/EmployeeInfo simple.xsd">

    <!-- XML Comment for: Employee -->
    <e:Employee EmployeeNumber="1">
        <!-- XML Comment for: Name -->
        <e:Name>Masashi Okamura</e:Name>
        <e:Department>Design Department</e:Department>
        <e:Telephone>03-1452-4567</e:Telephone>
        <e:Email>okamura@xmltr.co.jp</e:Email>
    </e:Employee>
    <e:Employee EmployeeNumber="2">
        <e:Name>Aiko Tanaka</e:Name>
        <e:Department>Sales Department</e:Department>
        <e:Telephone>03-6459-98764</e:Telephone>
        <e:Email>tanaka@xmltr.co.jp</e:Email>
    </e:Employee>
</e:EmployeeInfo>
