=== ElmarDott/TP-CORE/src/test/resources/org/europa/together/xml/simple.dtd
<!ELEMENT EmployeeInfo (Employee)*>
<!ELEMENT Employee (Name, Department, Telephone, Email)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Department (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ATTLIST Employee EmployeeNumber CDATA #REQUIRED>

=== ElmarDott/TP-CORE/src/test/resources/org/europa/together/xml/MixtedGrammar.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE EmployeeInfo SYSTEM "simple.dtd">

<EmployeeInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <Employee  EmployeeNumber="105">
        <Name>Masashi Okamura</Name>
        <Department>Design Department</Department>
        <Telephone>03-1452-4567</Telephone>
        <Email>okamura@xmltr.co.jp</Email>
    </Employee>
    <Employee  EmployeeNumber="109">
        <Name>Aiko Tanaka</Name>
        <Department>Sales Department</Department>
        <Telephone>03-6459-98764</Telephone>
        <Email>tanaka@xmltr.co.jp</Email>
    </Employee>
</EmployeeInfo>

=== ElmarDott/TP-CORE/src/test/resources/org/europa/together/xml/test_dtd_valid.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE EmployeeInfo SYSTEM "simple.dtd">

<EmployeeInfo>
    <Employee  EmployeeNumber="105">
        <Name>Masashi Okamura</Name>
        <Department>Design Department</Department>
        <Telephone>03-1452-4567</Telephone>
        <Email>okamura@xmltr.co.jp</Email>
    </Employee>
    <Employee  EmployeeNumber="109">
        <Name>Aiko Tanaka</Name>
        <Department>Sales Department</Department>
        <Telephone>03-6459-98764</Telephone>
        <Email>tanaka@xmltr.co.jp</Email>
    </Employee>
</EmployeeInfo>

=== ElmarDott/TP-CORE/src/test/resources/org/europa/together/xml/unformattedXml.xml
<?xml version="1.0" encoding="UTF-8"?><!-- THIs Is AN XML COMMENT -->
<!DOCTYPE EmployeeInfo SYSTEM "simple.dtd">
<EmployeeInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:e="http://www.sample.com/EmployeeInfo"           xsi:schemaLocation="http://www.sample.com/EmployeeInfo simple.xsd"><!-- THIs Is AN XML COMMENT -->
    <Employee EmployeeNumber="1"> <!-- THIs Is AN XML COMMENT -->
        <Name>Masashi Okamura</Name>
        <Department>Design Department</Department>
        <Telephone>03-1452-4567</Telephone>
        <Email>okamura@xmltr.co.jp<!-- THIs Is AN XML COMMENT --></Email>
        <Email>okamura@xmltr.co.jp<!-- THIs Is AN XML COMMENT --></Email>
        <XXX>
            <ABC>03-1452-4567</ABC>
        </XXX>
    </Employee>
    <Employee EmployeeNumber="2">
        <Name>Aiko Tanaka</Name>
        <Department>Sales Department</Department>
        <Telephone>03-6459-98764</Telephone>
        <Email>tanaka@xmltr.co.jp</Email>
    </Employee>
</EmployeeInfo>
